[package]
name = "kai"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
confy = "0.5.1"
dirs = "4.0.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"
spinners = "4.1.0"
