name: HOMEBREW-RELEASE

on:
  push:
   branches: [ master ]
   # tags:
   #   - '*'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: clippy

    - name: Build
      run: cargo build --release

    - name: Tar
      run: ./brew/run.sh

    - name: Set SHA
      id: shasum
      run: |
        echo ::set-output name=sha::"$(shasum -a 256 ./brew/kai.tar.gz | awk '{printf $1}')"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: 
          ./brew/*.tar.gz

      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Extract version
      id: extract-version
      run: |
        printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

    - name: Bump homebrew
    - uses: mislav/bump-homebrew-formula-action@v2
      if: "!contains(github.ref, '-')" # skip prereleases
      with:
        formula-name: kai
        formula-path: Formula/kai.rb
        homebrew-tap: kaspar1ndustries/homebrew-kai
        base-branch: master
        download-url: https://github.com/kaspar1ndustries/kai/releases/download/${{ steps.get_version.outputs.version }}/kai.tar.gz
        commit-message: |
          {{formulaName}} {{version}}

      env:
        COMMITTER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

